/* WAPI One V35.4 - facturation recurrente sans intervention mensuelle */
(()=>{'use strict';
  const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),euro=v=>Number(v||0).toLocaleString('fr-BE',{style:'currency',currency:'EUR'});
  const months=['','Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'];
  let emitters=[],running=false,manualPeriod=new Date().toISOString().slice(0,7);
  const isoToday=()=>new Date().toISOString().slice(0,10),monthStart=s=>String(s).slice(0,7)+'-01';
  function addMonths(s,n){const [y,m]=s.split('-').map(Number),d=new Date(Date.UTC(y,m-1+n,1));return d.toISOString().slice(0,10)}
  function endOfMonth(s){const [y,m]=s.split('-').map(Number);return new Date(Date.UTC(y,m,0)).toISOString().slice(0,10)}
  function contractStart(c){return c.starts_on||`${c.contract_year||String(c.year_label||'').match(/20\d{2}/)?.[0]||new Date().getFullYear()}-${String(c.start_month||1).padStart(2,'0')}-01`}
  function contractEnd(c){return c.ends_on||endOfMonth(`${c.contract_year||String(c.year_label||'').match(/20\d{2}/)?.[0]||new Date().getFullYear()}-${String(c.end_month||12).padStart(2,'0')}-01`)}
  function emitter(id){return emitters.find(x=>String(x.id)===String(id))||{}}
  async function loadEmitters(){const r=await supabaseClient.from('compta_billing_issuers').select('*').order('company_name');if(!r.error)emitters=r.data||[]}
  function emitterOptions(id=''){return '<option value="">Choisir…</option>'+emitters.filter(x=>x.active!==false).map(x=>`<option value="${x.id}" ${String(x.id)===String(id)?'selected':''}>${esc(x.company_name)}</option>`).join('')}
  function coproOptions(id=''){return (state.copros||[]).filter(x=>x.archived!==true).map(x=>`<option value="${x.id}" ${String(x.id)===String(id)?'selected':''}>${esc(x.name)}</option>`).join('')}
  function accountOptions(id=''){return typeof v23AccountOptions==='function'?v23AccountOptions(id,true):(state.accounts||[]).map(x=>`<option value="${x.id}" ${String(x.id)===String(id)?'selected':''}>${esc(x.code+' · '+x.label)}</option>`).join('')}
  function dueMonths(c){
    if(c.auto_account!==true||c.active===false||c.contract_status==='stopped')return[];
    let cursor=monthStart(c.billing_from||contractStart(c)),end=monthStart(contractEnd(c)),limit=monthStart(isoToday()),out=[];
    if(end>limit)end=limit;
    while(cursor<=end){out.push(cursor);cursor=addMonths(cursor,1)}return out;
  }
  function invoiceFor(c,date){return (state.syndicInvoices||[]).find(i=>String(i.contract_id)===String(c.id)&&Number(i.period_year)===Number(date.slice(0,4))&&Number(i.period_month)===Number(date.slice(5,7)))}
  function pendingPeriods(c){return dueMonths(c).filter(d=>!invoiceFor(c,d))}
  function unexported(){return (state.syndicInvoices||[]).filter(i=>i.status==='issued'&&!i.clearfact_exported_at&&i.clearfact_export_status!=='exported')}
  function invoiceState(i){
    if(i.status==='draft')return {label:'Brouillon à comptabiliser',cls:'warn'};
    if(i.clearfact_exported_at||i.clearfact_export_status==='exported')return {label:'Comptabilisée · exportée Clearfact',cls:'ok'};
    if(i.status==='issued')return {label:'Comptabilisée · PDF à exporter',cls:'ok'};
    return {label:i.status||'À contrôler',cls:'warn'};
  }

  function recurringDraftPayload(c,date){
    const y=Number(date.slice(0,4)),m=Number(date.slice(5,7)),t=v23InvoiceTotals(c.monthly_amount_htva,c.vat_rate),day=String(Math.min(Number(c.due_day||15),28)).padStart(2,'0');
    return {invoice_number:`DRAFT-${c.id}-${y}${String(m).padStart(2,'0')}`,billing_type:c.service_family==='cleaning'?'service':'honoraires',contract_id:c.id,issuer_id:c.issuer_id,copro_id:c.copro_id,customer_name:(state.copros||[]).find(x=>String(x.id)===String(c.copro_id))?.name||'',invoice_date:date,due_date:`${y}-${String(m).padStart(2,'0')}-${day}`,period_year:y,period_month:m,description:`${c.label} - ${months[m]} ${y}`,account_id:c.account_id,account_code:c.account_code,amount_subtotal:t.subtotal,vat_rate:Number(c.vat_rate||0),vat_amount:t.vat,amount_total:t.total,status:'draft',created_by:currentUser?.id||null};
  }
  async function createDraft(c,date){
    const existing=invoiceFor(c,date);if(existing)return existing;
    const payload=recurringDraftPayload(c,date);
    const ins=await supabaseClient.from('compta_syndic_invoices').insert(payload).select('*, compta_copros(name,optipro_ref,address)').single();if(ins.error)throw ins.error;
    state.syndicInvoices=state.syndicInvoices||[];state.syndicInvoices.push(ins.data);
    return ins.data;
  }
  async function createAndPost(c,date){
    if(invoiceFor(c,date))return false;
    const draft=await createDraft(c,date);await postSyndicInvoiceV24(draft.id,true);return true;
  }
  async function automateContract(c){let count=0;for(const date of pendingPeriods(c)){if(await createAndPost(c,date))count++}await supabaseClient.from('compta_syndic_billing_contracts').update({last_automation_at:new Date().toISOString()}).eq('id',c.id);return count}
  async function runAutomation(show=true,onlyId=''){
    if(running)return;running=true;let count=0;
    try{for(const c of (state.syndicContracts||[]).filter(x=>x.auto_account===true&&(!onlyId||String(x.id)===String(onlyId))))count+=await automateContract(c);await loadSyndicBillingV23();if(show)alert(count?`${count} facture(s) créée(s) et comptabilisée(s).`:'Tout est déjà à jour.');render354();}
    catch(e){alert('Automatisation interrompue : '+e.message)}finally{running=false}
  }

  function render354(){
    const root=$('syndicBillingContent');if(!root)return;const contracts=state.syndicContracts||[],active=contracts.filter(c=>c.auto_account===true&&c.active!==false&&c.contract_status!=='stopped'),due=active.reduce((n,c)=>n+pendingPeriods(c).length,0),exports=unexported();
    const currentTab=state.syndicBillingTab||'campaigns';
    if(currentTab==='contracts')return renderContracts354(root,contracts);
    if(currentTab==='invoices'||currentTab==='exports')return renderInvoiceHistory354(root,currentTab==='exports');
    if(currentTab!=='campaigns')return false;
    root.innerHTML=`<div class="w354-hero"><div><h2>Facturation récurrente</h2><p>Les contrats automatiques sont comptabilisés seuls. Les contrats manuels sont traités dans le poste mensuel ci-dessous.</p></div><div class="w354-actions"><button class="btn secondary" id="w354RunNow">Vérifier les automatiques</button><button class="btn" id="w354ExportAll" ${exports.length?'':'disabled'}>Exporter ${exports.length} PDF Clearfact</button></div></div><div class="w354-kpis"><div class="w354-kpi"><span>Contrats automatiques actifs</span><strong>${active.length}</strong></div><div class="w354-kpi"><span>Échéances automatiques manquantes</span><strong>${due}</strong></div><div class="w354-kpi"><span>Factures comptabilisées</span><strong>${(state.syndicInvoices||[]).filter(i=>i.status==='issued').length}</strong></div><div class="w354-kpi"><span>PDF à exporter</span><strong>${exports.length}</strong></div></div>${renderManualDesk354(contracts)}<div class="w354-help">Une facture portant un numéro officiel est déjà comptabilisée dans les factures fournisseurs de la copropriété.</div><div class="card"><div class="w353-toolbar"><div><h3>File Clearfact</h3><p>Une ligne correspond à un PDF individuel.</p></div></div><div class="w354-export-row" style="font-weight:800;background:#f7f8fb"><span></span><span>N°</span><span>Société</span><span>Copropriété / libellé</span><span>Date</span><span>Montant</span></div>${exports.map(i=>`<div class="w354-export-row"><input type="checkbox" data-w354-export="${i.id}" checked><strong>${esc(i.invoice_number||'')}</strong><span>${esc(emitter(i.issuer_id).company_name||'')}</span><span>${esc((i.compta_copros?.name||i.customer_name||'')+' · '+(i.description||''))}</span><span>${esc(i.invoice_date||'')}</span><strong>${euro(i.amount_total)}</strong></div>`).join('')||'<div class="notice">Aucun PDF en attente : tout a été exporté.</div>'}</div>`;
  }
  function manualContractsForPeriod(contracts){const d=manualPeriod+'-01';return contracts.filter(c=>c.auto_account!==true&&c.active!==false&&c.contract_status!=='stopped'&&monthStart(contractStart(c))<=d&&monthStart(contractEnd(c))>=d)}
  function renderManualDesk354(contracts){const rows=manualContractsForPeriod(contracts),date=manualPeriod+'-01';return `<div class="card w354-manual"><div class="w353-toolbar"><div><h3>Comptabilisation manuelle mensuelle</h3><p>Choisis le mois, puis prépare ou comptabilise uniquement les contrats manuels.</p></div><div class="w354-actions"><input id="w354ManualPeriod" type="month" value="${manualPeriod}"><button class="btn secondary" id="w354PrepareManualAll" ${rows.length?'':'disabled'}>Préparer les manquantes</button><button class="btn" id="w354PostManualAll" ${rows.some(c=>invoiceFor(c,date)?.status==='draft')?'':'disabled'}>Comptabiliser les brouillons</button></div></div>${rows.map(c=>{const i=invoiceFor(c,date),st=!i?['À préparer','warn']:i.status==='draft'?['Prête à comptabiliser','warn']:['Comptabilisée','ok'];return `<div class="w354-manual-row"><span><strong>${esc(emitter(c.issuer_id).company_name||'')}</strong><small>${esc(c.compta_copros?.name||'')} · ${esc(c.label||'')}</small></span><strong>${euro(c.monthly_amount_htva)} HTVA</strong><span class="badge ${st[1]}">${st[0]}</span><span class="w354-actions">${!i?`<button class="btn secondary small" data-w354-prepare-manual="${c.id}">Préparer</button>`:i.status==='draft'?`<button class="btn small" data-w354-post="${i.id}">Comptabiliser</button>`:`<button class="btn secondary small" data-preview-syndic-invoice="${i.id}">PDF</button>`}</span></div>`}).join('')||'<div class="notice">Aucun contrat manuel actif pour ce mois.</div>'}</div>`}
  function renderInvoiceHistory354(root,onlyToExport=false){
    const f=state.w354InvoiceFilter||{search:'',issuer:'',status:onlyToExport?'to_export':'all'};if(onlyToExport)f.status='to_export';state.w354InvoiceFilter=f;
    let rows=[...(state.syndicInvoices||[])].sort((a,b)=>String(b.invoice_date||b.created_at||'').localeCompare(String(a.invoice_date||a.created_at||'')));
    rows=rows.filter(i=>!f.issuer||String(i.issuer_id)===String(f.issuer)).filter(i=>{if(f.status==='draft')return i.status==='draft';if(f.status==='issued')return i.status==='issued';if(f.status==='to_export')return i.status==='issued'&&!i.clearfact_exported_at&&i.clearfact_export_status!=='exported';if(f.status==='exported')return !!(i.clearfact_exported_at||i.clearfact_export_status==='exported');return true}).filter(i=>!f.search||[i.invoice_number,i.description,i.customer_name,i.compta_copros?.name,emitter(i.issuer_id).company_name].join(' ').toLowerCase().includes(f.search.toLowerCase()));
    root.innerHTML=`<div class="w354-hero"><div><h2>${onlyToExport?'Export Clearfact':'Historique des factures récurrentes'}</h2><p>${onlyToExport?'Uniquement les PDF comptabilisés qui n’ont pas encore été exportés.':'Toutes les factures restent visibles ici, même après leur export.'}</p></div><div class="w354-actions"><button class="btn secondary" id="w354OpenSupplierInvoices">Voir dans les factures fournisseurs</button>${onlyToExport?`<button class="btn" id="w354ExportHistory" ${rows.length?'':'disabled'}>Exporter la sélection</button>`:''}</div></div><div class="list-filters"><label>Recherche<input id="w354InvoiceSearch" value="${esc(f.search)}" placeholder="Numéro, copropriété, libellé…"></label><label>Société<select id="w354InvoiceIssuer"><option value="">Toutes</option>${emitters.map(x=>`<option value="${x.id}" ${String(f.issuer)===String(x.id)?'selected':''}>${esc(x.company_name)}</option>`).join('')}</select></label>${onlyToExport?'':`<label>État<select id="w354InvoiceStatus"><option value="all">Tous</option><option value="draft">Brouillons</option><option value="issued">Comptabilisées</option><option value="to_export">À exporter</option><option value="exported">Exportées</option></select></label>`}</div><div class="card"><div class="w354-history-row w354-history-head"><span></span><span>Facture</span><span>Société / copropriété</span><span>Période</span><span>Montant</span><span>État</span><span>Actions</span></div>${rows.map(i=>{const st=invoiceState(i);return `<div class="w354-history-row"><input type="checkbox" data-w354-export="${i.id}" ${i.status==='issued'&&!i.clearfact_exported_at&&i.clearfact_export_status!=='exported'?'checked':'disabled'}><span><strong>${esc(i.invoice_number||'Brouillon')}</strong><small>${esc(i.description||'')}</small></span><span><strong>${esc(emitter(i.issuer_id).company_name||'')}</strong><small>${esc(i.compta_copros?.name||i.customer_name||'')}</small></span><span>${months[Number(i.period_month)]||''} ${i.period_year||''}</span><strong>${euro(i.amount_total)}</strong><span><span class="badge ${st.cls}">${st.label}</span></span><span class="w354-actions"><button class="btn secondary small" data-preview-syndic-invoice="${i.id}">PDF</button>${i.status==='draft'?`<button class="btn small" data-w354-post="${i.id}">Comptabiliser</button>`:''}</span></div>`}).join('')||'<div class="notice">Aucune facture dans ce filtre.</div>'}</div>`;
    if($('w354InvoiceStatus'))$('w354InvoiceStatus').value=f.status;
  }
  function renderContracts354(root,contracts){
    root.innerHTML=`<div class="w354-hero"><div><h2>Contrats de facturation</h2><p>Crée le contrat une fois. WAPI One gère ensuite les mensualités arrivées à échéance.</p></div><button class="btn" id="w354NewContract">+ Nouveau contrat</button></div><div class="card"><div class="w354-contract" style="font-weight:800;background:#f7f8fb"><span>Société / copropriété</span><span>Service</span><span>Montant</span><span>Période / automatisation</span><span></span></div>${contracts.map(c=>{const stopped=c.active===false||c.contract_status==='stopped',made=(state.syndicInvoices||[]).filter(i=>String(i.contract_id)===String(c.id)).length;return `<div class="w354-contract"><span><strong>${esc(emitter(c.issuer_id).company_name||'Émetteur')}</strong><small>${esc(c.compta_copros?.name||'')}</small></span><span>${esc(c.label||'')}<small>${c.service_family==='cleaning'?'Nettoyage / entretien':'Honoraires / service'}</small></span><strong>${euro(c.monthly_amount_htva)} HTVA</strong><span><span class="w354-progress"><i class="w354-dot ${stopped?'stop':c.auto_account?'ok':''}"></i>${stopped?'Arrêté':c.auto_account?'Automatique':'Manuel'}</span><small>${esc(contractStart(c))} → ${esc(contractEnd(c))} · ${made} facture(s)</small></span><span class="w354-contract-actions"><button class="btn secondary small" data-w354-edit="${c.id}">Modifier</button><button class="btn secondary small" data-w353-renew="${c.id}">Renouveler / indexer</button>${stopped?'':`<button class="btn danger small" data-w354-stop="${c.id}">Arrêter</button>`}<button class="btn danger small" data-w354-delete="${c.id}">Supprimer</button></span></div>`}).join('')||'<div class="notice">Aucun contrat créé.</div>'}</div>`;
  }

  function openContract354(id=''){
    const c=(state.syndicContracts||[]).find(x=>String(x.id)===String(id))||{issuer_id:emitters[0]?.id||'',copro_id:state.activeCoproId||'',service_family:'syndic_fee',label:'Honoraires mensuels',monthly_amount_htva:0,vat_rate:21,due_day:15,starts_on:`${new Date().getFullYear()}-01-01`,ends_on:`${new Date().getFullYear()}-12-31`,auto_account:true,active:true};
    const past=(!id||c.auto_account!==true)&&monthStart(contractStart(c))<monthStart(isoToday());
    const html=`<div class="popup-form"><div class="form-grid"><label>Société émettrice<select id="w354Issuer">${emitterOptions(c.issuer_id)}</select></label><label>Copropriété cliente<select id="w354Copro">${coproOptions(c.copro_id)}</select></label><label>Type de service<select id="w354Family"><option value="syndic_fee">Honoraires syndic</option><option value="cleaning">Nettoyage / entretien</option><option value="other">Autre service</option></select></label><label>Libellé<input id="w354Label" value="${esc(c.label||'')}"></label><label>Montant mensuel HTVA<input id="w354Amount" type="number" step="0.01" value="${Number(c.monthly_amount_htva||0)}"></label><label>TVA (%)<input id="w354Vat" type="number" step="0.01" value="${Number(c.vat_rate??21)}"></label><label>Compte comptable<select id="w354Account">${accountOptions(c.account_id)}</select></label><label>Jour d'échéance<input id="w354Due" type="number" min="1" max="28" value="${Number(c.due_day||15)}"></label><label>Début du contrat<input id="w354Start" type="date" value="${esc(contractStart(c))}"></label><label>Fin du contrat<input id="w354End" type="date" value="${esc(contractEnd(c))}"></label><label>Automatisation<select id="w354Auto"><option value="true">Créer et comptabiliser automatiquement</option><option value="false">Mode manuel</option></select></label></div><div id="w354Catchup" class="w354-catchup ${past?'':'hidden'}"><label>Démarrage dans le passé<select id="w354CatchupChoice"><option value="yes">Oui, comptabiliser tous les mois depuis le début</option><option value="no">Non, commencer au mois actuel</option></select></label></div></div>`;
    openAppModal(id?'Modifier le contrat':'Nouveau contrat récurrent',html,`<button class="btn secondary" data-modal-close>Annuler</button><button class="btn" id="w354SaveContract" data-id="${id}">Enregistrer et activer</button>`,{size:'wide'});$('w354Family').value=c.service_family||'syndic_fee';$('w354Auto').value=String(c.auto_account!==false);$('w354Start').onchange=()=>{$('w354Catchup').classList.toggle('hidden',(!id||c.auto_account!==true)?monthStart($('w354Start').value)>=monthStart(isoToday()):true)};
  }
  async function saveContract354(id=''){
    const acc=$('w354Account'),start=$('w354Start').value,end=$('w354End').value,catchup=$('w354CatchupChoice')?.value||'yes',isPast=monthStart(start)<monthStart(isoToday()),existing=(state.syndicContracts||[]).find(x=>String(x.id)===String(id)),auto=$('w354Auto').value==='true',activating=auto&&existing?.auto_account!==true;
    const billingFrom=isPast&&(!id||activating)&&catchup==='no'?monthStart(isoToday()):(existing?.billing_from&&!activating?existing.billing_from:start);
    const p={issuer_id:$('w354Issuer').value||null,copro_id:$('w354Copro').value||null,service_family:$('w354Family').value,label:$('w354Label').value.trim(),monthly_amount_htva:Number($('w354Amount').value||0),vat_rate:Number($('w354Vat').value||0),account_id:acc.value||null,account_code:acc.selectedOptions?.[0]?.dataset?.code||null,due_day:Number($('w354Due').value||15),starts_on:start,ends_on:end,billing_from:billingFrom,start_month:Number(start.slice(5,7)),end_month:Number(end.slice(5,7)),contract_year:Number(start.slice(0,4)),year_label:start.slice(0,4),auto_account:auto,active:true,contract_status:'active',updated_at:new Date().toISOString()};
    if(!p.issuer_id||!p.copro_id||!p.label||!p.monthly_amount_htva||!p.account_id||!start||!end)return alert('Complète la société, la copropriété, le libellé, le montant, le compte et la période.');if(end<start)return alert('La fin du contrat doit être postérieure au début.');
    let r=id?await supabaseClient.from('compta_syndic_billing_contracts').update(p).eq('id',id).select('*, compta_copros(name)').single():await supabaseClient.from('compta_syndic_billing_contracts').insert({...p,created_by:currentUser?.id||null}).select('*, compta_copros(name)').single();if(r.error)return alert(r.error.message);
    closeAppModal();await loadSyndicBillingV23();if(p.auto_account)await runAutomation(true,r.data.id);state.syndicBillingTab='contracts';render354();
  }
  async function stopContract(id){if(!confirm('Arrêter ce contrat ? Les factures déjà comptabilisées restent intactes et aucune nouvelle mensualité ne sera créée.'))return;const r=await supabaseClient.from('compta_syndic_billing_contracts').update({active:false,contract_status:'stopped',stopped_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id);if(r.error)return alert(r.error.message);await loadSyndicBillingV23();render354()}
  async function deleteContract(id){const inv=(state.syndicInvoices||[]).filter(i=>String(i.contract_id)===String(id)),issued=inv.filter(i=>i.status==='issued');if(issued.length)return alert(`Suppression impossible : ce contrat a déjà produit ${issued.length} facture(s) comptabilisée(s). Utilise Arrêter.`);if(!confirm('Supprimer ce contrat créé par erreur et ses éventuels brouillons ?'))return;if(inv.length)await supabaseClient.from('compta_syndic_invoices').delete().in('id',inv.map(i=>i.id));const r=await supabaseClient.from('compta_syndic_billing_contracts').delete().eq('id',id);if(r.error)return alert(r.error.message);await loadSyndicBillingV23();render354()}
  async function exportSelected(){const ids=[...document.querySelectorAll('[data-w354-export]:checked')].map(x=>x.dataset.w354Export),rows=unexported().filter(i=>ids.includes(String(i.id)));if(!rows.length)return alert('Sélectionne au moins une facture.');if(!window.JSZip)return alert('Le module ZIP est indisponible.');const zip=new JSZip();for(const i of rows){const em=emitter(i.issuer_id),blob=await syndicInvoicePdfBlobV23(i),folder=(em.code||'FACTURES').replace(/[^A-Z0-9_-]/gi,'_');zip.file(`${folder}/${String(i.invoice_number||i.id).replace(/[^A-Z0-9_-]/gi,'_')}.pdf`,blob)}const blob=await zip.generateAsync({type:'blob'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Clearfact_${isoToday()}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);const r=await supabaseClient.from('compta_syndic_invoices').update({clearfact_export_status:'exported',clearfact_exported_at:new Date().toISOString(),updated_at:new Date().toISOString()}).in('id',ids);if(r.error)return alert(r.error.message);await loadSyndicBillingV23();render354()}
  async function postDraft354(id){try{await postSyndicInvoiceV24(id,true);await loadAll();await loadSyndicBillingV23();render354()}catch(e){alert('Comptabilisation impossible : '+e.message)}}
  async function prepareManual354(id){try{const c=(state.syndicContracts||[]).find(x=>String(x.id)===String(id));if(!c)return;await createDraft(c,manualPeriod+'-01');await loadSyndicBillingV23();render354()}catch(e){alert('Préparation impossible : '+e.message)}}
  async function prepareAllManual354(){try{for(const c of manualContractsForPeriod(state.syndicContracts||[]))await createDraft(c,manualPeriod+'-01');await loadSyndicBillingV23();render354()}catch(e){alert('Préparation impossible : '+e.message)}}
  async function postAllManual354(){try{const ids=manualContractsForPeriod(state.syndicContracts||[]).map(c=>invoiceFor(c,manualPeriod+'-01')).filter(i=>i?.status==='draft').map(i=>i.id);if(!ids.length)return alert('Aucun brouillon manuel pour ce mois.');if(!confirm(`Comptabiliser ${ids.length} facture(s) manuelle(s) ?`))return;for(const id of ids)await postSyndicInvoiceV24(id,true);await loadAll();await loadSyndicBillingV23();render354()}catch(e){alert('Comptabilisation impossible : '+e.message)}}

  const previousRender=typeof renderSyndicBillingV23==='function'?renderSyndicBillingV23:null;if(previousRender)renderSyndicBillingV23=function(){const tab=state.syndicBillingTab||'campaigns';if(['campaigns','contracts','invoices','exports'].includes(tab))return render354();return previousRender()};
  const previousRenderV25=typeof renderSyndicBillingV25==='function'?renderSyndicBillingV25:null;if(previousRenderV25)renderSyndicBillingV25=function(){const tab=state.syndicBillingTab||'campaigns';if(['campaigns','contracts','invoices','exports'].includes(tab))return render354();return previousRenderV25()};
  if(typeof openSyndicContractModalV23==='function')openSyndicContractModalV23=openContract354;
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='w354NewContract'||b.id==='newSyndicContractBtn2')return openContract354();if(b.dataset.w354Edit)return openContract354(b.dataset.w354Edit);if(b.id==='w354SaveContract')return saveContract354(b.dataset.id);if(b.dataset.w354Stop)return stopContract(b.dataset.w354Stop);if(b.dataset.w354Delete)return deleteContract(b.dataset.w354Delete);if(b.id==='w354RunNow')return runAutomation(true);if(b.id==='w354ExportAll'||b.id==='w354ExportHistory')return exportSelected();if(b.dataset.w354Post)return postDraft354(b.dataset.w354Post);if(b.dataset.w354PrepareManual)return prepareManual354(b.dataset.w354PrepareManual);if(b.id==='w354PrepareManualAll')return prepareAllManual354();if(b.id==='w354PostManualAll')return postAllManual354();if(b.id==='w354OpenSupplierInvoices'){state.invoiceFilters=state.invoiceFilters||{};state.invoiceFilters.source='syndic_billing';return switchToView('invoices')}});
  document.addEventListener('change',e=>{if(e.target.id==='w354InvoiceIssuer'){state.w354InvoiceFilter.issuer=e.target.value;render354()}if(e.target.id==='w354InvoiceStatus'){state.w354InvoiceFilter.status=e.target.value;render354()}if(e.target.id==='w354ManualPeriod'){manualPeriod=e.target.value;render354()}});
  document.addEventListener('input',e=>{if(e.target.id==='w354InvoiceSearch'){state.w354InvoiceFilter.search=e.target.value;render354();$('w354InvoiceSearch')?.focus()}});
  document.addEventListener('DOMContentLoaded',()=>setTimeout(async()=>{await loadEmitters();if(typeof loadSyndicBillingV23==='function')await loadSyndicBillingV23();await runAutomation(false);if(!$('syndicBillingView')?.classList.contains('hidden'))render354()},1900));
})();
