/* WAPI One V36.3 — contexte exercice, facturation, tiers et navigation. */
(()=>{'use strict';window.WAPI_ONE_VERSION='V36.3';window.WAPI_ONE_BUILD_DATE='2026-08-05';
const $=id=>document.getElementById(id),esc=v=>typeof escapeHtml==='function'?escapeHtml(String(v??'')):String(v??'');
const billingFilter={manager:'',copro:''};let lastCopro=null,globalSuppliers=false,syncing=false;
const managerId=c=>String(c?.manager_user_id||c?.manager_id||c?.gestionnaire_id||''),profileName=p=>p?.display_name||p?.full_name||p?.name||p?.email||'Utilisateur';
function cleanNavigation(){document.querySelectorAll('[data-view="suppliers"]').forEach(b=>b.remove());document.querySelectorAll('[data-view="owners"] .nav-label,#moduleTabs [data-view="owners"] span').forEach(n=>n.textContent='Tiers');const title=$('ownersView')?.querySelector('.toolbar h2');if(title)title.textContent='Tiers';}
function currentYearFor(cid){const today=new Date().toISOString().slice(0,10),ys=(state.fiscalYears||[]).filter(y=>String(y.copro_id)===String(cid));return ys.find(y=>y.starts_on<=today&&y.ends_on>=today)||ys.filter(y=>y.status!=='closed').sort((a,b)=>String(b.starts_on||'').localeCompare(String(a.starts_on||'')))[0]||ys.sort((a,b)=>String(b.starts_on||'').localeCompare(String(a.starts_on||'')))[0]||null;}
function propagateYear(y){if(!y)return;['budgetFiscalYearFilter','callsFiscalYearFilter','settlementYearFilter','thirdBalanceYearFilter','v356BilanYear','v28MeterYear'].forEach(id=>{const el=$(id);if(el&&[...el.options].some(o=>String(o.value)===String(y.id)))el.value=y.id;});if($('v28AccountLookupFrom'))$('v28AccountLookupFrom').value=y.starts_on||'';if($('v28AccountLookupTo'))$('v28AccountLookupTo').value=y.ends_on||'';}
function syncYear(force=false){if(syncing)return;const s=$('activeFiscalYearSelect'),cid=state.activeCoproId||'';if(!s)return;syncing=true;const changed=String(lastCopro??'')!==String(cid);lastCopro=cid;if(!cid){s.innerHTML='<option value="">Mode global — aucun exercice unique</option>';s.value='';state.activeFiscalYearId='';syncing=false;return;}const ys=(state.fiscalYears||[]).filter(y=>String(y.copro_id)===String(cid)).sort((a,b)=>String(b.starts_on||'').localeCompare(String(a.starts_on||'')));const y=(!force&&!changed?ys.find(x=>String(x.id)===String(state.activeFiscalYearId)):null)||currentYearFor(cid);s.innerHTML=ys.map(x=>`<option value="${esc(x.id)}">${x.status==='closed'?'🔴':'🟢'} ${esc(x.year_code||x.code||x.label||'Exercice')} — ${esc(x.starts_on||'')} / ${esc(x.ends_on||'')}</option>`).join('')||'<option value="">Aucun exercice — créez-en un dans les réglages copro</option>';s.value=y?.id||'';state.activeFiscalYearId=y?.id||'';if(y){localStorage.setItem('wapi-one-active-fiscal-year',y.id);propagateYear(y);}syncing=false;}
function onTopYearChange(){const id=$('activeFiscalYearSelect')?.value||'',y=(state.fiscalYears||[]).find(x=>String(x.id)===String(id));state.activeFiscalYearId=id;localStorage.setItem('wapi-one-active-fiscal-year',id);propagateYear(y);setTimeout(()=>{try{renderAll();}catch(_){ }},0);}
function enhanceBilling(){if($('syndicBillingView')?.classList.contains('hidden')||state.syndicBillingTab!=='contracts')return;const root=$('syndicBillingContent');if(!root)return;let bar=$('v363BillingFilters');if(!bar){bar=document.createElement('div');bar.id='v363BillingFilters';bar.className='v363-billing-filters';root.querySelector('.w354-hero')?.after(bar);}const profiles=(state.userProfiles||[]).filter(p=>p.active!==false),allowed=(state.copros||[]).filter(c=>!billingFilter.manager||managerId(c)===String(billingFilter.manager));if(billingFilter.copro&&!allowed.some(c=>String(c.id)===String(billingFilter.copro)))billingFilter.copro='';const count=(state.syndicContracts||[]).filter(c=>allowed.some(x=>String(x.id)===String(c.copro_id))&&(!billingFilter.copro||String(c.copro_id)===String(billingFilter.copro))).length;bar.innerHTML=`<label>Gestionnaire<select id="v363BillingManager"><option value="">Tous les gestionnaires</option>${profiles.map(p=>`<option value="${esc(p.id)}" ${String(p.id)===String(billingFilter.manager)?'selected':''}>${esc(profileName(p))}</option>`).join('')}</select></label><label>Copropriété<select id="v363BillingCopro"><option value="">Toutes les copropriétés autorisées</option>${allowed.map(c=>`<option value="${esc(c.id)}" ${String(c.id)===String(billingFilter.copro)?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><span class="badge">${count} contrat(s)</span>`;root.querySelectorAll('.w354-contract').forEach((row,i)=>{if(i===0)return;const id=row.querySelector('[data-w354-edit]')?.dataset.w354Edit,c=(state.syndicContracts||[]).find(x=>String(x.id)===String(id));row.hidden=!c||!allowed.some(x=>String(x.id)===String(c.copro_id))||Boolean(billingFilter.copro&&String(c.copro_id)!==String(billingFilter.copro));});}
function openServices(){state.syndicBillingTab='services';if(typeof renderSyndicBillingV23==='function')renderSyndicBillingV23();}
function enhanceTiers(){cleanNavigation();return window.WapiTiersV364?.render?.();}
function renderGlobalSuppliers(){const host=$('ownersTable');if(!host)return;const rows=(state.suppliers||[]).filter(s=>s.active!==false);host.innerHTML=`<div class="v363-global-supplier-note">Répertoire global : ${rows.length} fournisseur(s), toutes copropriétés confondues. Ouvre une fiche pour gérer ses copropriétés.</div><div class="table-wrap"><table><thead><tr><th>Code</th><th>Fournisseur</th><th>E-mail</th><th>TVA</th><th></th></tr></thead><tbody>${rows.map(s=>`<tr><td>${esc(s.code||s.supplier_code||'')}</td><td><strong>${esc(s.name||'')}</strong></td><td>${esc(s.email||'')}</td><td>${esc(s.vat_number||s.vat||'')}</td><td><button class="btn secondary small" data-open-identity="supplier|${esc(s.id)}" type="button">Ouvrir / copropriétés</button></td></tr>`).join('')}</tbody></table></div>`;$('v363AllSuppliers').textContent='Revenir aux fournisseurs de la copropriété';}
async function deleteOwner(id){const o=(state.owners||[]).find(x=>String(x.id)===String(id));if(!o)return;const lots=(state.lots||[]).filter(x=>String(x.owner_id)===String(id)).length,calls=(state.ownerCalls||[]).filter(x=>String(x.owner_id)===String(id)).length,entries=(state.entries||[]).filter(x=>String(x.owner_id||x.tier_id)===String(id)).length;if(lots||calls||entries)return alert(`Suppression impossible : ${lots} lot(s), ${calls} appel(s) et ${entries} écriture(s) sont liés à ce copropriétaire.`);if(!confirm(`Supprimer définitivement ${o.display_name||o.name||'ce copropriétaire'} ?`))return;const r=await supabaseClient.from('compta_owners').delete().eq('id',id);if(r.error)return alert(r.error.message);state.owners=state.owners.filter(x=>String(x.id)!==String(id));renderOwners?.();enhanceTiers();}
function enhancePdfFrame(){document.querySelectorAll('.v362-preview-frame').forEach(frame=>{if(frame.dataset.v363Logo)return;const apply=()=>{frame.dataset.v363Logo='1';const doc=frame.contentDocument,logo=window.WapiPdfTheme?.logoDataUrl;if(!doc||!logo)return;doc.querySelectorAll('.logo,.invoice-print-logo').forEach(el=>{el.textContent='';const img=doc.createElement('img');img.src=logo;img.alt='WAPI SYNDIK';img.style.cssText='display:block;max-width:42mm;max-height:28mm;width:auto;height:auto;object-fit:contain';el.appendChild(img);});};frame.addEventListener('load',apply,{once:true});if(frame.contentDocument?.readyState==='complete')apply();});}
const oldBilling=typeof renderSyndicBillingV23==='function'?renderSyndicBillingV23:null;if(oldBilling)renderSyndicBillingV23=function(){const out=oldBilling.apply(this,arguments);setTimeout(enhanceBilling,0);return out;};const oldRender=typeof renderAll==='function'?renderAll:null;if(oldRender)renderAll=function(){const out=oldRender.apply(this,arguments);setTimeout(()=>{syncYear();cleanNavigation();enhanceBilling();enhanceTiers();enhancePdfFrame();},0);return out;};
document.addEventListener('click',e=>{const service=e.target.closest?.('[data-v25-syndic-tab="services"],[data-v23-syndic-tab="services"],[data-syndic-tab="services"]');if(service){e.preventDefault();e.stopImmediatePropagation();openServices();return;}if(e.target.closest?.('#v363AllSuppliers')){globalSuppliers=!globalSuppliers;if(globalSuppliers)renderGlobalSuppliers();else{renderOwners?.();setTimeout(enhanceTiers,0);}return;}const del=e.target.closest?.('[data-v363-delete-owner]');if(del){e.preventDefault();e.stopImmediatePropagation();deleteOwner(del.dataset.v363DeleteOwner);return;}setTimeout(()=>{cleanNavigation();enhanceTiers();enhancePdfFrame();},40);},true);
document.addEventListener('change',e=>{if(e.target.id==='v363BillingManager'){billingFilter.manager=e.target.value;billingFilter.copro='';enhanceBilling();}if(e.target.id==='v363BillingCopro'){billingFilter.copro=e.target.value;enhanceBilling();}if(e.target.id==='activeFiscalYearSelect')onTopYearChange();if(e.target.id==='activeCoproSelect')setTimeout(()=>{syncYear(true);try{renderAll();}catch(_){ }},80);if(e.target.id==='callDispatchCoproFilter'&&!e.target.value)setTimeout(()=>{e.target.value='';window.WapiCallDispatchV361?.render?.();},0);},true);
const install=()=>{syncYear(true);cleanNavigation();enhanceBilling();enhanceTiers();enhancePdfFrame();};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,1300));else setTimeout(install,1300);})();
